## Naive Baye's Machine Learning Algorithms Implementation

In [1]:
from sklearn.datasets import load_iris

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X,y=load_iris(return_X_y=True)

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [8]:
X_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2

In [10]:
from sklearn.naive_bayes import GaussianNB

In [11]:
gnb=GaussianNB()

In [12]:
gnb.fit(X_train,y_train)

GaussianNB()

In [13]:
y_pred=gnb.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [17]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [114]:
import seaborn as sns

In [115]:
df=sns.load_dataset('tips')

In [116]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [118]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [119]:
## independnent and dependent features
X=df[['total_bill','tip', 'sex', 'smoker', 'day', 'size']]
y=df['time']

In [120]:
##train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [126]:
X_train.head(2)

total_bill       tip   sex smoker  day  size
58   -0.979646 -0.881111  Male    Yes  Sat     2
1    -1.082206 -0.952733  Male     No  Sun     3

In [125]:
## Standardize the dataset
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[['total_bill', 'tip']]=scaler.fit_transform(X_train[['total_bill', 'tip']])
X_test[['total_bill', 'tip']]=scaler.transform(X_test[['total_bill', 'tip']])

In [127]:
print("df['sex'].value_counts()", "\n", df['sex'].value_counts(), "\n\n")
print("df['smoker'].value_counts()", "\n", df['smoker'].value_counts(), "\n\n")
print("df['day'].value_counts()", "\n", df['day'].value_counts(), "\n\n")
print("df['time'].value_counts()", "\n", df['time'].value_counts(), "\n\n")

df['sex'].value_counts() 
 sex
Male      157
Female     87
Name: count, dtype: int64 


df['smoker'].value_counts() 
 smoker
No     151
Yes     93
Name: count, dtype: int64 


df['day'].value_counts() 
 day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64 


df['time'].value_counts() 
 time
Dinner    176
Lunch      68
Name: count, dtype: int64 




In [128]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()

In [129]:
import warnings
warnings.filterwarnings('ignore')
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['smoker']=le2.fit_transform(X_train['smoker'])

In [130]:
X_test['sex']=le1.transform(X_test['sex'])
X_test['smoker']=le2.transform(X_test['smoker'])

In [131]:
## Onehot encoding--- ColumnTrnasformer

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [132]:
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[4])],
                                   remainder='passthrough')

In [133]:
X_train

total_bill       tip  sex  smoker   day  size
58    -0.979646 -0.881111    1       1   Sat     2
1     -1.082206 -0.952733    1       0   Sun     3
2      0.133695  0.365117    1       0   Sun     3
68     0.044810 -0.702055    1       0   Sat     2
184    2.360377  0.007006    1       1   Sun     2
..          ...       ...  ...     ...   ...   ...
64    -0.256031 -0.250835    1       0   Sat     3
15     0.198649  0.665931    1       0   Sun     2
228   -0.747178 -0.193537    1       0   Sat     2
125    1.135360  0.866473    0       0  Thur     6
9     -0.576245  0.171737    1       0   Sun     2

[183 rows x 6 columns]

In [134]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train=ct.fit_transform(X_train)

In [135]:
X_train

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -9.79646103e-01, -8.81110683e-01,  1.00000000e+00,
         1.00000000e+00,  2.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        -1.08220565e+00, -9.52732970e-01,  1.00000000e+00,
         0.00000000e+00,  3.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         1.33694814e-01,  3.65117113e-01,  1.00000000e+00,
         0.00000000e+00,  3.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.48098687e-02, -7.02054965e-01,  1.00000000e+00,
         0.00000000e+00,  2.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         2.36037665e+00,  7.00567727e-03,  1.00000000e+00,
         1.00000000e+00,  2.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        -1.16653240e+00,  7.23228549e-01,  0.00000000e+00,
         1.00000000e+00,  2.00000000e+00],
       [ 0.00000000e+00,  1.000000

In [136]:
X_test

total_bill       tip  sex  smoker   day  size
162   -0.413289 -0.709217    0       0   Sun     3
60     0.051647  0.157412    1       1   Sat     2
61    -0.686782 -0.709217    1       1   Sat     2
63    -0.176263  0.551335    1       1   Sat     4
69    -0.550036 -0.644757    1       1   Sat     2
..          ...       ...  ...     ...   ...   ...
201   -0.808714 -0.702055    0       1  Thur     2
149   -1.404698 -0.709217    1       0  Thur     2
175    1.488620  0.085790    1       1   Sun     2
226   -1.110694 -0.709217    0       1   Fri     2
49    -0.204752  0.007006    1       0   Sun     2

[61 rows x 6 columns]

In [137]:
X_test=ct.transform(X_test)

In [138]:
X_test

array([[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
        -4.13289464e-01, -7.09217194e-01,  0.00000000e+00,
         0.00000000e+00,  3.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         5.16471722e-02,  1.57412480e-01,  1.00000000e+00,
         1.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -6.86781604e-01, -7.09217194e-01,  1.00000000e+00,
         1.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.76262944e-01,  5.51335059e-01,  1.00000000e+00,
         1.00000000e+00,  4.00000000e+00],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -5.50035534e-01, -6.44757136e-01,  1.00000000e+00,
         1.00000000e+00,  2.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.46355034e+00,  1.43945142e+00,  1.00000000e+00,
         1.00000000e+00,  2.00000000e+00],
       [ 0.00000000e+00,  1.000000

In [139]:
from sklearn.naive_bayes import GaussianNB

In [140]:
gnb=GaussianNB()

In [141]:
gnb.fit(X_train,y_train)

GaussianNB()

In [142]:
y_pred=gnb.predict(X_test)

In [143]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [144]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[41  0]
 [ 2 18]]
0.9672131147540983
              precision    recall  f1-score   support

      Dinner       0.95      1.00      0.98        41
       Lunch       1.00      0.90      0.95        20

    accuracy                           0.97        61
   macro avg       0.98      0.95      0.96        61
weighted avg       0.97      0.97      0.97        61

