In [71]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [72]:
df = pd.read_csv(r"sample.csv")

In [73]:
print(df)
print(df.info())

     models  year  price
0      Alto  2000     12
1     Grand  2001     23
2       i20  2002     34
3  Ecosport  2000     45
4   Wagon R  2002     56
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   models  5 non-null      object
 1   year    5 non-null      int64 
 2   price   5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None


### encoder experiment

In [33]:
encoder = OneHotEncoder()

In [34]:
encoded = encoder.fit_transform(df[['models']])

In [35]:
encoded_arr = encoded.toarray()
encoded_arr

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [36]:
encoder.get_feature_names_out()

array(['models_Alto', 'models_Ecosport', 'models_Grand', 'models_Wagon R',
       'models_i20'], dtype=object)

#### with OneHotEncoder(drop='first') and observe difference
observations: 1st feature is dropped

In [53]:
encoder = OneHotEncoder(drop='first')
encoded = encoder.fit_transform(df[['models']])
encoded_arr = encoded.toarray()
encoded_arr

array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [54]:
encoder.get_feature_names_out()

array(['models_Ecosport', 'models_Grand', 'models_Wagon R', 'models_i20'],
      dtype=object)

###

In [74]:
# Create Column Transformer with 3 types of transformers
num_features = ['price']
onehot_columns = ['models']

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, onehot_columns),
        ("StandardScaler", numeric_transformer, num_features)
        
    ]
)

In [75]:
df=preprocessor.fit_transform(df)

In [76]:
print(df)
print(f'type(df): {type(df)}')

[[ 1.          0.          0.          0.          0.         -1.41421356]
 [ 0.          0.          1.          0.          0.         -0.70710678]
 [ 0.          0.          0.          0.          1.          0.        ]
 [ 0.          1.          0.          0.          0.          0.70710678]
 [ 0.          0.          0.          1.          0.          1.41421356]]
type(df): <class 'numpy.ndarray'>


In [77]:
df = pd.DataFrame(df, columns=preprocessor.get_feature_names_out())

In [78]:
df

OneHotEncoder__models_Alto  OneHotEncoder__models_Ecosport  \
0                         1.0                             0.0   
1                         0.0                             0.0   
2                         0.0                             0.0   
3                         0.0                             1.0   
4                         0.0                             0.0   

   OneHotEncoder__models_Grand  OneHotEncoder__models_Wagon R  \
0                          0.0                            0.0   
1                          1.0                            0.0   
2                          0.0                            0.0   
3                          0.0                            0.0   
4                          0.0                            1.0   

   OneHotEncoder__models_i20  StandardScaler__price  
0                        0.0              -1.414214  
1                        0.0              -0.707107  
2                        1.0               0.000000  
3                        0.0               0.707107  
4                        0.0               1.414214